- name: Debian desktop config
  hosts: vm
  gather_facts: yes
  become: no
  vars:
    github_username: "martinlillebo"
#  vars_prompt:
#    - name: github_username
#      prompt: GitHub-brukernavn
#      private: false
#    - name: github_access_token
#      prompt: Lim inn GitHub access token (ctrl + shift + V)
#      private: true

  tasks:

  - name: Legger til locale en_US.UTF-8
    become: true
    locale_gen:
      name: en_US.UTF-8
      state: present
    register: locale

  - name: Legger til locale C
    become: true
    locale_gen:
      name: C
      state: present
    register: locale

  - name: Legger til locale en_DK.UTF-8
    become: true
    locale_gen:
      name: en_DK.UTF-8
      state: present
    register: locale

  - name: setter LC_TIME=en_DK
    become: yes
    command: localectl set-locale LC_TIME=en_DK.UTF-8
    when: locale.changed  

  - name: setter LC_MESSAGES=C
    become: yes
    command: localectl set-locale LC_MESSAGES=C
    when: locale.changed

  - name: Inkluderer variabler
    ansible.builtin.include_vars: secret-vars.yml

  - name: apt update og apt upgrade
    become: yes
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600 # hopper over update_cache om den er under en time gammel
      upgrade: yes

  - name: Installerer masse programmer
    become: yes
    ansible.builtin.apt:
      state: present
      name:
        - virt-manager          # Til KVM
        - qemu-system           # Til KVM
        - libvirt-daemon-system # Til KVM
        - flatpak
        - git
        - curl
        - htop
        - python3-pip
        - python3-venv
        - less
        - lshw
        - nano
        - tmux
        - tree
        - usbutils
        - ufw
        - yamllint
        - net-tools
        - ncat
        - ethtool
        - host
        - ncdu
        - screenkey
        - autokey-gtk # Autokey til GNOME
        - zsh
        - python3-psutil # Avhengighet til community.general.dconf. Burde ligge i venv
        - vlc
        - shutter
        - jq
        - neofetch
        - ansible

  - name: Add Flathub repository
    become: yes
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

  - name: Installerer Zotero fra Flathub
    become: yes
    community.general.flatpak:
      name: org.zotero.Zotero
      state: present

  - name: Installerer Standard Notes fra Flathub
    become: yes
    community.general.flatpak:
      name:  org.standardnotes.standardnotes
      state: present

  - name: Installerer Spotify fra Flathub
    become: yes
    community.general.flatpak:
      name:  com.spotify.Client
      state: present

  - name: Installerer Slack fra Flathub
    become: yes
    community.general.flatpak:
      name:  com.slack.Slack
      state: present

  - name: Installerer Discord fra Flathub
    become: yes
    community.general.flatpak:
      name:  com.discordapp.Discord
      state: present

  - name: Installerer GIMP fra Flathub
    become: yes
    community.general.flatpak:
      name: org.gimp.GIMP
      state: present    

  - name: Installerer Steam fra Flathub
    become: yes
    community.general.flatpak:
      name: com.valvesoftware.Steam
      state: present    

  - name: Installerer VSCode fra Flathub
    become: yes
    community.general.flatpak:
      name: com.visualstudio.code
      state: present    

  - name: Installerer Teams fra Flathub
    become: yes
    community.general.flatpak:
      name: com.github.IsmaelMartinez.teams_for_linux
      state: present    


#  - name: Installerer XX fra Flathub
#    become: yes
#    community.general.flatpak:
#      name: 
#      state: present    

#  - name: Importerer GNOME-hurtigtaster
#    import_role:
#      name: gnome-hurtigtaster

  - name: Git-config
    community.general.git_config:
      name: pull.rebase
      scope: global
      value: 'false'

  - name: Setter global Git user.name
    community.general.git_config:
      name: user.name
      value: "Martin Lillebo"
      scope: global

  - name: Setter global Git user.email
    community.general.git_config:
      name: user.email
      value: "{{ e_mail_address }}"
      scope: global

  - name: Oppretter "~/repos/notater/" 
    ansible.builtin.file:
      path: "~/repos/notater"
      state: directory

  - name: Sjekker om notatblokka fins
    stat:
      path: "{{ ansible_env.HOME }}/repos/notater/.git/"
    register: notater_fins

  - name: Kopierer inn notatblokka
    ansible.builtin.git:
      repo: "https://{{ github_username }}:{{ github_access_token }}@github.com/martinlillebo/notater.git"
      dest: "{{ ansible_env.HOME }}/repos/notater"
      version: master
    when: not notater_fins.stat.exists

  - name: Sjekker om ~/.ssh fins
    stat:
      path: "{{ ansible_env.HOME }}/.ssh/"
    register: ssh_fins
  
  - name: Opprettet et SSH-nøkkelpar
    ansible.builtin.openssh_keypair:
      path: ~/.ssh/id_ed25519
      type: ed25519
      comment: "lillebomartin@gmail.com"
    register: ssh_key

  - name: Setter Zsh som standard skall
    become: true
    ansible.builtin.user:
      name: "{{ ansible_facts['env']['USER'] }}"
      shell: /bin/zsh

  - name: Sjekker om Oh My Zsh er installert ennå
    stat:
      path: "{{ ansible_env.HOME }}/.oh-my-zsh"
    register: ohmyzsh_installed

  - name: Laster ned OMZ installasjonsskript
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /tmp/install_ohmyzsh.sh
    when: not ohmyzsh_installed.stat.exists

  - name: Installerer OMZ
    command: sh /tmp/install_ohmyzsh.sh --unattended
    register: ohmyzsh_result
    failed_when: "'FAILED' in ohmyzsh_result.stderr"
    when: not ohmyzsh_installed.stat.exists

  - name: Henter Git-repoet som gir syntaksmarkering i Zsh
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: ~/zsh-syntax-highlighting
      update: yes

  - name: Oppretter "~/repos/dotfiler/" 
    ansible.builtin.file:
      path: "~/repos/notater"
      state: directory

  - name: Kopierer inn dotfilene
    ansible.builtin.git:
      repo: "https://github.com/martinlillebo/dotfiler.git"
      dest: "{{ ansible_env.HOME }}/repos/dotfiler"
      version: master

  - name: Henter info om ~/.zshrc
    ansible.builtin.stat:
      path: ~/.zshrc
    register: zshrc_stat    

  - name: Sletter original .zshrc hvis den fins
    ansible.builtin.file:
      path: ~/.zshrc
      state: absent
    when: not zshrc_stat.stat.islnk

  - name: symlenker .zshrc til ~/repos/dotfiler/.zshrc
    ansible.builtin.file:
      src: ~/repos/dotfiler/.zshrc
      dest: ~/.zshrc
      state: link
    when: not zshrc_stat.stat.islnk

  - name: symlenker .vimrc
    ansible.builtin.file:
      src: ~/repos/dotfiler/.vimrc
      dest: ~/.vimrc
      state: link

  - name: symlenker .nanorc
    ansible.builtin.file:
      src: ~/repos/dotfiler/.nanorc
      dest: ~/.nanorc
      state: link

  - name: Setter rett tidssone
    community.general.timezone:
      name: Europe/Oslo

 # - name: Alle facts
 #   ansible.builtin.debug:
 #     var: ansible_facts

#  - name: printtest
#    ansible.builtin.debug:
#      msg: "Current user: {{ ansible_facts['env']['USER'] }}"

#  - name: Legger inn AutoKey-config
#    import_role:
#      name: autokey-config

#  Fjerner midlertidig for å spare tid
#  - name: Legger inn sublimeless .desktop til ./local/share/applications
#    import_role:
#      name: sublimeless-desktop
