- name: Debian desktop config
  hosts: vm
  gather_facts: yes
  become: no
  vars:
    github_username: "martinlillebo"
#  vars_prompt:
#    - name: github_username
#      prompt: GitHub-brukernavn
#      private: false
#    - name: github_access_token
#      prompt: Lim inn GitHub access token (ctrl + shift + V)
#      private: true

  roles:
    - locale-innstillinger
    - gnome-config
#    - autokey-config
    - ssh-innstillinger
    - terminalprogrammer
    - zsh-omz
    - flatpak-programmer
    - git-config
    - clone-notater
    - clone-dotfiler
    - clone-ansible-desktop
    - sublimeless-desktop

  pre_tasks:

  - name: Inkluderer variabler
    ansible.builtin.include_vars: secret-vars.yml

  - name: Setter rett tidssone
    community.general.timezone:
      name: Europe/Oslo
