- name: Debian desktop config
  hosts: vm
  gather_facts: yes
  become: no
  vars:
    github_username: "martinlillebo"

  roles:
    - terminalprogrammer
    - git-config
    - ssh-innstillinger
    - locale-innstillinger
    - zsh-omz
    - gnome-config
    - clone-notater
    - clone-dotfiler
    - clone-ansible-desktop
    - docker-installering
    - flatpak-programmer
    - etc-config
    - sublimeless-desktop
    - keyd-installering
    - autokey-config
    - emacs
    - emacs-purge

  pre_tasks:

  - name: Inkluderer variabler
    ansible.builtin.include_vars: secret-vars.yml

  - name: Setter rett tidssone
    community.general.timezone:
      name: Europe/Oslo
