- name: Debian desktop config
  hosts: vm
  gather_facts: yes
  become: no
  vars:
    github_username: "martinlillebo"
#  vars_prompt:
#    - name: github_username
#      prompt: GitHub-brukernavn
#      private: false
#    - name: github_access_token
#      prompt: Lim inn GitHub access token (ctrl + shift + V)
#      private: true

  tasks:

  - name: Endre locale-innstillinger
    import_role:
      name: locale-innstillinger

  - name: Inkluderer variabler
    ansible.builtin.include_vars: secret-vars.yml

  - name: apt update og apt upgrade
    become: yes
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600 # hopper over update_cache om den er under en time gammel
      upgrade: yes

  - name: Setter rett tidssone
    community.general.timezone:
      name: Europe/Oslo

  - name: Installerer masse programmer
    become: yes
    ansible.builtin.apt:
      state: present
      name:
        - virt-manager          # Til KVM
        - qemu-system           # Til KVM
        - libvirt-daemon-system # Til KVM
        - git
        - curl
        - htop
        - python3-pip
        - python3-venv
        - less
        - lshw
        - nano
        - tmux
        - tree
        - usbutils
        - ufw
        - yamllint
        - net-tools
        - ncat
        - ethtool
        - host
        - ncdu
        - screenkey
        - autokey-gtk # Autokey til GNOME
        - zsh
        - python3-psutil # Avhengighet til community.general.dconf. Burde ligge i venv
        - vlc
        - shutter
        - jq
        - neofetch
        - ansible

#  - name: Importerer GNOME-hurtigtaster
#    import_role:
#      name: gnome-hurtigtaster

  - name: Installerer flatpaks
    import_role:
      name: flatpak-programmer

  - name: Git-konfigurasjon: 
    import_role:
      name: git-config

  - name: Legger inn dotfiler
    import_role:
      name: dotfiler

  - name: Endrer skall til Zsh + OMZ
    import_role:
      name: zsh-omz 

  - name: Oppretter "~/repos/notater/" 
    ansible.builtin.file:
      path: "~/repos/notater"
      state: directory

  - name: Sjekker om notatblokka fins
    stat:
      path: "{{ ansible_env.HOME }}/repos/notater/.git/"
    register: notater_fins

  - name: Kopierer inn notatblokka
    ansible.builtin.git:
      repo: "https://{{ github_username }}:{{ github_access_token }}@github.com/martinlillebo/notater.git"
      dest: "{{ ansible_env.HOME }}/repos/notater"
      version: master
    when: not notater_fins.stat.exists

  - name: Sjekker om ~/.ssh fins
    stat:
      path: "{{ ansible_env.HOME }}/.ssh/"
    register: ssh_fins
  
  - name: Opprettet et SSH-nøkkelpar
    ansible.builtin.openssh_keypair:
      path: ~/.ssh/id_ed25519
      type: ed25519
      comment: "lillebomartin@gmail.com"
    register: ssh_key


 # - name: Alle facts
 #   ansible.builtin.debug:
 #     var: ansible_facts

#  - name: printtest
#    ansible.builtin.debug:
#      msg: "Current user: {{ ansible_facts['env']['USER'] }}"

#  - name: Legger inn AutoKey-config
#    import_role:
#      name: autokey-config

#  Fjerner midlertidig for å spare tid
#  - name: Legger inn sublimeless .desktop til ./local/share/applications
#    import_role:
#      name: sublimeless-desktop
