- name: Debian desktop config
  hosts: vm
  gather_facts: yes
  become: no
  vars:
    github_username: "martinlillebo"
#  vars_prompt:
#    - name: github_username
#      prompt: GitHub-brukernavn
#      private: false
#    - name: github_access_token
#      prompt: Lim inn GitHub access token (ctrl + shift + V)
#      private: true

  roles:
    - locale-innstillinger
    - terminalprogrammer
    - gnome-config
#    - autokey-config
    - ssh-innstillinger
    - zsh-omz
    - flatpak-programmer
    - git-config
    - clone-notater
    - clone-dotfiler
    - clone-ansible-desktop
    - sublimeless-desktop

  pre_tasks:

  - name: Installerer Keyd
    become: yes
    ansible.builtin.git:
      repo: https://github.com/rvaiya/keyd.git
      dest: ~/keyd
      version: v2.5.0

  - name: Build Keyd
    become: yes
    ansible.builtin.make:
      chdir: ~/keyd

  - name: Install Keyd
    become: yes
    ansible.builtin.command:
      cmd: make install
      chdir: ~/keyd

  - name: Enable and start Keyd service
    become: yes
    ansible.builtin.systemd:
      name: keyd
      enabled: yes
      state: started


#- name: Git checkout
#  ansible.builtin.git:
#    repo: 'https://foosball.example.org/path/to/repo.git'
#    dest: /srv/checkout
#    version: release-0.22

  - name: Inkluderer variabler
    ansible.builtin.include_vars: secret-vars.yml

  - name: Setter rett tidssone
    community.general.timezone:
      name: Europe/Oslo
