- name: Debian desktop config
  hosts: vm
  gather_facts: yes
  become: no
  vars:
    github_username: "martinlillebo"
#  vars_prompt:
#    - name: github_username
#      prompt: GitHub-brukernavn
#      private: false
#    - name: github_access_token
#      prompt: Lim inn GitHub access token (ctrl + shift + V)
#      private: true

  roles:
    - autokey-config
    - terminalprogrammer
    - git-config
    - ssh-innstillinger
    - locale-innstillinger
    - zsh-omz
    - gnome-config
    - clone-notater
    - clone-dotfiler
    - clone-ansible-desktop
    - docker-installering
    - keyd-installering
    - flatpak-programmer
    - sublimeless-desktop

  pre_tasks:

#- name: Git checkout
#  ansible.builtin.git:
#    repo: 'https://foosball.example.org/path/to/repo.git'
#    dest: /srv/checkout
#    version: release-0.22

  - name: Inkluderer variabler
    ansible.builtin.include_vars: secret-vars.yml

  - name: Setter rett tidssone
    community.general.timezone:
      name: Europe/Oslo