  - name: Installerer avhengigheter
    become: yes
    ansible.builtin.apt:
      state: present
      name:
        - curl
        - ca-certificates

  - name: Oppretter /etc/apt/keyrings/
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'
  
  - name: Laster ned Docker som GPG-nøkkel
    become: yes
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'

  - name: Legger til Docker-repositoriet til apt sources
    become: yes
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ docker_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      state: present
      filename: docker
    register: docker_repo_lagt_til

  - name: Update apt package index after adding Docker repository
    become: yes
    ansible.builtin.apt:
      update_cache: yes
      force_apt_get: yes
    when: docker_repo_lagt_til.changed

  - name: Installerer avhengigheter
    become: yes
    ansible.builtin.apt:
      state: present
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin