  - name: apt update og apt upgrade
    become: yes
    ansible.builtin.apt:
      update_cache: yes
      upgrade: yes

  - name: Installerer masse programmer
    become: yes
    ansible.builtin.apt:
      state: present
      name:
        - ansible
        - arp-scan
        - autokey-gtk # Autokey til GNOME
        - curl
        - ethtool
        - git
        - host
        - htop
        - jq
        - less
        - libvirt-daemon-system # Til KVM
        - lshw
        - nano
        - neofetch
        - ncat
        - ncdu
        - net-tools
        - python3-pip
        - python3-psutil # Avhengighet til community.general.dconf. Burde ligge i venv
        - python3-venv
        - qemu-system           # Til KVM
        - ripgrep
        - shutter
        - screenkey
        - terminator
        - tmux
        - tree
        - usbutils
        - ufw
        - virt-manager          # Til KVM
        - vlc
        - yamllint
        - zsh
        - xclip

  - name: Add Microsoft GPG key
    become: yes
    ansible.builtin.apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Add VSCode repo
    become: yes
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
      state: present

  - name: Update apt cache
    become: yes
    ansible.builtin.apt:
      update_cache: yes

  - name: Install VSCode
    become: yes
    ansible.builtin.apt:
      name: code
      state: present
