  - name: apt update og apt upgrade
    become: yes
    ansible.builtin.apt:
      update_cache: yes
      upgrade: yes

  - name: Installerer masse programmer
    become: yes
    ansible.builtin.apt:
      state: present
      name:
        - ansible
        - arp-scan
        - autokey-gtk # Autokey til GNOME
        - curl
        - ethtool
        - git
        - host
        - htop
        - jq
        - less
        - libvirt-daemon-system # Til KVM
        - lshw
        - nano
        - neofetch
        - ncat
        - ncdu
        - net-tools
        - python3-pip
        - python3-psutil # Avhengighet til community.general.dconf. Burde ligge i venv
        - python3-venv
        - qemu-system           # Til KVM
        - shutter
        - screenkey
        - terminator
        - tmux
        - tree
        - usbutils
        - ufw
        - virt-manager          # Til KVM
        - vlc
        - yamllint
        - zsh
        - xclip
