- name: Laster ned Renés Sublimeless-release og pakker den ut 
  ansible.builtin.unarchive:
    src: https://github.com/renerocksai/sublimeless_zk/releases/download/sublimeless_zk-pre-0.9/sublimeless_zk-pre-0.9-linux.tar.gz
    dest: ~/Downloads/
    remote_src: yes
    creates: ~/Downloads/sublimeless_zk-pre-0.9-linux/ 

- name: Kopierer sublimeless .desktop-filen til ~/.local/share/applications
  copy:
    src: sublimeless.desktop
    dest: ~/.local/share/applications

